#!/usr/bin/perl -w
use strict;
use warnings;

our $VERSION = "1.000";

use Cwd qw(abs_path);
use FindBin qw($Bin);

my $base_dir = abs_path($Bin);
$base_dir =~ s{/t/*\z}{} ||
    die "test directory '$base_dir' does not seem to end on /t";

# We depend on the --blib option to get blib/lib in @INC
exec($^X, "-MDevel::Cover=-silent,1", "$base_dir/bin/adb_fake", @ARGV);
